"""Remove is_active column from vehicles table

Revision ID: 0ba0e5367a0f
Revises: 2834a7864bf9
Create Date: 2025-09-19 12:06:01.767203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ba0e5367a0f'
down_revision = '2834a7864bf9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'vehicles',
        sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
