"""add_reservations_table_with_correct_foreign_keys

Revision ID: 0ba625ce5d8d
Revises: 5be2c0aaa182
Create Date: 2025-09-13 06:44:54.053640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0ba625ce5d8d'
down_revision = '5be2c0aaa182'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'reservations',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('confirmation_number', sa.String(length=20), nullable=False),
        sa.Column('customer_id', sa.Integer(), nullable=False),
        sa.Column('vehicle_id', sa.UUID(), nullable=False),
        sa.Column('pickup_store_id', sa.UUID(), nullable=False),
        sa.Column('return_store_id', sa.UUID(), nullable=False),
        sa.Column('pickup_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column('return_datetime', sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            'actual_pickup_datetime', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column(
            'actual_return_datetime', sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column('status', sa.String(length=20), nullable=False),
        sa.Column('base_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('duration_hours', sa.Integer(), nullable=False),
        sa.Column('subtotal', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            'options', postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            'option_fees', sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            'insurance_fee', sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column('tax_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
        sa.Column(
            'discount_amount', sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column(
            'member_discount', sa.DECIMAL(precision=10, scale=2), nullable=True
        ),
        sa.Column('points_used', sa.Integer(), nullable=True),
        sa.Column('points_earned', sa.Integer(), nullable=True),
        sa.Column('special_requests', sa.Text(), nullable=True),
        sa.Column('staff_notes', sa.Text(), nullable=True),
        sa.Column('cancellation_reason', sa.Text(), nullable=True),
        sa.Column('payment_method', sa.String(length=20), nullable=True),
        sa.Column('payment_status', sa.String(length=20), nullable=True),
        sa.Column('payment_reference', sa.String(length=100), nullable=True),
        sa.Column(
            'created_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.Column(
            'updated_at',
            sa.DateTime(timezone=True),
            server_default=sa.text('now()'),
            nullable=True
        ),
        sa.ForeignKeyConstraint(['customer_id'], ['users.id']),
        sa.ForeignKeyConstraint(['pickup_store_id'], ['stores.id']),
        sa.ForeignKeyConstraint(['return_store_id'], ['stores.id']),
        sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id']),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('confirmation_number')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reservations')
    # ### end Alembic commands ###
