"""remove staff role from UserRole enum

Revision ID: 2834a7864bf9
Revises: e2a6020f52bd
Create Date: 2025-09-19 03:54:23.224785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2834a7864bf9'
down_revision = 'e2a6020f52bd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
