"""add image_filename to vehicles table

Revision ID: 5be2c0aaa182
Revises: 96a4969128bf
Create Date: 2025-09-13 05:21:03.675627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5be2c0aaa182'
down_revision = '96a4969128bf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('image_filename', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'image_filename')
    # ### end Alembic commands ###
