"""Migrate User ID from Integer to UUID

Revision ID: 959ad9c520b7
Revises: fd6c252b5317
Create Date: 2025-09-15 07:43:37.109764

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '959ad9c520b7'
down_revision = 'fd6c252b5317'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add new UUID column to users table
    op.add_column('users', sa.Column('uuid_id', sa.UUID(), nullable=True))
    
    # Step 2: Generate UUIDs for existing users
    op.execute("""
        UPDATE users 
        SET uuid_id = gen_random_uuid()
        WHERE uuid_id IS NULL
    """)
    
    # Step 3: Make uuid_id not nullable
    op.alter_column('users', 'uuid_id', nullable=False)
    
    # Step 4: Add new UUID column to reservations table
    op.add_column('reservations', sa.Column('customer_uuid_id', sa.UUID(), nullable=True))
    
    # Step 5: Populate customer_uuid_id based on existing customer_id
    op.execute("""
        UPDATE reservations 
        SET customer_uuid_id = u.uuid_id
        FROM users u
        WHERE reservations.customer_id = u.id
    """)
    
    # Step 6: Make customer_uuid_id not nullable
    op.alter_column('reservations', 'customer_uuid_id', nullable=False)
    
    # Step 7: Drop old foreign key constraint
    op.drop_constraint('reservations_customer_id_fkey', 'reservations', type_='foreignkey')
    
    # Step 8: Drop old columns
    op.drop_column('reservations', 'customer_id')
    op.drop_column('users', 'id')
    
    # Step 9: Rename new columns
    op.alter_column('users', 'uuid_id', new_column_name='id')
    op.alter_column('reservations', 'customer_uuid_id', new_column_name='customer_id')
    
    # Step 10: Add primary key constraint
    op.create_primary_key('users_pkey', 'users', ['id'])
    
    # Step 11: Add foreign key constraint
    op.create_foreign_key('reservations_customer_id_fkey', 'reservations', 'users', ['customer_id'], ['id'])
    
    # Step 12: Update options column type
    op.alter_column('reservations', 'options',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Step 1: Add new Integer column to users table
    op.add_column('users', sa.Column('int_id', sa.INTEGER(), nullable=True))
    
    # Step 2: Generate sequential IDs for existing users
    op.execute("""
        UPDATE users 
        SET int_id = row_number() OVER (ORDER BY created_at)
        WHERE int_id IS NULL
    """)
    
    # Step 3: Make int_id not nullable
    op.alter_column('users', 'int_id', nullable=False)
    
    # Step 4: Add new Integer column to reservations table
    op.add_column('reservations', sa.Column('customer_int_id', sa.INTEGER(), nullable=True))
    
    # Step 5: Populate customer_int_id based on existing customer_id
    op.execute("""
        UPDATE reservations 
        SET customer_int_id = u.int_id
        FROM users u
        WHERE reservations.customer_id = u.id
    """)
    
    # Step 6: Make customer_int_id not nullable
    op.alter_column('reservations', 'customer_int_id', nullable=False)
    
    # Step 7: Drop old foreign key constraint
    op.drop_constraint('reservations_customer_id_fkey', 'reservations', type_='foreignkey')
    
    # Step 8: Drop old columns
    op.drop_column('reservations', 'customer_id')
    op.drop_column('users', 'id')
    
    # Step 9: Rename new columns
    op.alter_column('users', 'int_id', new_column_name='id')
    op.alter_column('reservations', 'customer_int_id', new_column_name='customer_id')
    
    # Step 10: Add primary key constraint
    op.create_primary_key('users_pkey', 'users', ['id'])
    
    # Step 11: Add foreign key constraint
    op.create_foreign_key('reservations_customer_id_fkey', 'reservations', 'users', ['customer_id'], ['id'])
    
    # Step 12: Update options column type
    op.alter_column('reservations', 'options',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ###
