"""Add is_smoking_allowed field to vehicles

Revision ID: e2a6020f52bd
Revises: 959ad9c520b7
Create Date: 2025-09-16 06:18:45.827574

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2a6020f52bd'
down_revision = '959ad9c520b7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.add_column('vehicles', sa.Column('is_smoking_allowed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_smoking_allowed')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    # ### end Alembic commands ###
