"""add_vehicles_table

Revision ID: f0c3a870a2ff
Revises: 001
Create Date: 2025-09-12 09:42:40.397196

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f0c3a870a2ff'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vehicles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('make', sa.String(length=50), nullable=False),
    sa.Column('model', sa.String(length=50), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=30), nullable=False),
    sa.Column('license_plate', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=20), nullable=False),
    sa.Column('class_type', sa.String(length=20), nullable=False),
    sa.Column('transmission', sa.String(length=10), nullable=False),
    sa.Column('fuel_type', sa.String(length=15), nullable=False),
    sa.Column('daily_rate', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('is_available', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_plate')
    )
    # SQLiteではALTER COLUMNの制限があるため、コメントアウト
    # op.alter_column('users', 'role',
    #            existing_type=postgresql.ENUM('customer', 'admin', 'staff', name='userrole'),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'is_active',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    # op.alter_column('users', 'is_verified',
    #            existing_type=sa.BOOLEAN(),
    #            server_default=None,
    #            existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               existing_nullable=False)
    op.alter_column('users', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('users', 'role',
               existing_type=postgresql.ENUM('customer', 'admin', 'staff', name='userrole'),
               server_default=sa.text("'customer'::userrole"),
               existing_nullable=False)
    op.drop_table('vehicles')
    # ### end Alembic commands ###
