"""add_store_id_to_vehicles

Revision ID: fd6c252b5317
Revises: 0ba625ce5d8d
Create Date: 2025-09-13 07:07:44.556990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd6c252b5317'
down_revision = '0ba625ce5d8d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('store_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'vehicles', 'stores', ['store_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'vehicles', type_='foreignkey')
    op.drop_column('vehicles', 'store_id')
    # ### end Alembic commands ###
